name: Test GitHub-Actions

env:
  AZURE_WEBAPP_NAME: ktor-demo-webapp
  JAVA_VERSION: '11'

on:
  push:
    branches: [ main ]
    paths-ignore:
      - README.md
      -
  pull_request:
    branches: [ main ]
    paths-ignore:
      - README.md

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest

    steps:
      - run: echo "The job was triggered by a ${{ github.event_name }} event."

      - run: echo "This job is running on a ${{ runner.os }} server hosted by GitHub"

      - run: echo "The name of the branch is ${{ github.ref }} and your repository is ${{ github.repository }}"

      - run: echo "${{ toJson(github) }}"
      - run: echo "${{ github.event.pusher.email }}"
      - id: teststep
        uses: cybaspace/hello-world-composite-action@v1
        with:
          who-to-greet: 'Me'
      - run: echo random-number ${{ steps.teststep.outputs.random-number }}
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'adopt'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      #- name: Gradle compile and test
      #  run: ./gradlew clean test

      - name: Create fat jar
        run: ./gradlew shadowJar --no-daemon

      - name: Conditional step ONLY for pull request
        if: ${{ github.event_name == 'pull_request' }}
        run: echo "You see this because it's a pull request"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.AZURE_WEBAPP_NAME }}
          path: '${{ github.workspace }}/build/libs/*-all.jar'

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: dockerfile
          path: '${{ github.workspace }}/Dockerfile'

  build-image:
    name: Build a container image
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Development'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: ${{ env.AZURE_WEBAPP_NAME }}

      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: dockerfile

      - name: Login to azure
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Build and tag image
        run: |
          echo "github.sha=$GITHUB_SHA"
          docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/${{ env.AZURE_WEBAPP_NAME }}:${{ github.sha }}
      - name: Scan image for vulnerabilities
        uses: Azure/container-scan@v0
        id: container-scan
        continue-on-error: true
        with:
          image-name: ${{ secrets.REGISTRY_LOGIN_SERVER }}/${{ env.AZURE_WEBAPP_NAME }}:${{ github.sha }}
      - name: Push Docker image
        run: |
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/${{ env.AZURE_WEBAPP_NAME }}:${{ github.sha }}
      - name: Post logs in appinsights
        uses: Azure/publish-security-assessments@v0
        with:
          scan-results-path: ${{ steps.container-scan.outputs.scan-report-path }}
          connection-string: ${{ secrets.AZ_APPINSIGHTS_CONNECTION_STRING }}
          subscription-token: ${{ secrets.AZ_SUBSCRIPTION_TOKEN }}

      - name: Send scan report with mail
        uses: dawidd6/action-send-mail@v3
        with:
          # Required mail server address:
          server_address: smtp.ionos.de
          # Required mail server port:
          server_port: 465
          # Optional (recommended): mail server username:
          username: ${{secrets.MAIL_USERNAME}}
          # Optional (recommended) mail server password:
          password: ${{secrets.MAIL_PASSWORD}}
          # Required mail subject:
          subject: ${{github.repository}} scan result
          # Required recipients' addresses:
          to: ${{ github.event.pusher.email }}
          # Required sender full name (address can be skipped):
          from: semjon@krolzik.de # <user@example.com>
          # Optional whether this connection use TLS (default is true if server_port is 465)
          secure: true
          body: Attached scan result of ${{github.repository}}
          attachments: ${{ steps.container-scan.outputs.scan-report-path }}

  deploy:
    name: Deploy WebApp to Azure
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Development'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: ${{ env.AZURE_WEBAPP_NAME }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          slot-name: 'production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_D76E313513DF4BB7B7678512D179D83D }}
          package: '*.jar'
